spring:
  application:
    name: user-service
server:
  port: 8081
eureka:
  client:
    refresh:
      enable: false
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
